### ISSUE TITLE
GtkTextViews are sometimes grey instead of white (including fix)

### ISSUE THREAD

**Issue by Gymnasiast** [matthewmx86/Redmond97#11]
Very visible in Xed:

![afbeelding](https://github.com/user-attachments/assets/6d1fcd7d-cddb-4e39-bc75-18b423b6755d)

This is, however, easy to fix, by adding the following to e.g. `gtk-view.css`:

```CSS
textview text,
grid viewport box box textview {
  background-color: @base_color; }
```

Which will fix it:

![afbeelding](https://github.com/user-attachments/assets/ee9134c6-8269-4016-99fc-dd4877269603)
